### ISSUE TITLE
Prevent colliding internal cache ids based on adapter

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-paginator#2] opened 2019-12-31 22:10 UTC
Resolves #41 
`json_encode($this->getAdapter())` would always return an empty object for `\Zend\Paginator\Adapter\DbSelect` adapters (i.e. `{}`). By performing `print_r` on the adapter we can get the current state which, in the case of `DbSelect`, includes an sql object containing table name, join details, where clause, etc.
This change will prevent collisions between adapters that do not have any public properties and/or values.

---

Originally posted by @richard-parnaby-king at https://github.com/zendframework/zend-paginator/pull/42

**Comment by froschdesign** [comment] 2020-06-18 19:38
Duplicate of #3

**Closed by froschdesign** 2020-06-18 19:38 UTC
Labels: Bug, Unit Test Needed
